# Generated by Django 4.2.16 on 2024-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("genre", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("pages", models.IntegerField()),
                ("cover", models.ImageField(upload_to="book_covers/")),
            ],
        ),
    ]
